export const quizzes = [
  [
    {
      quizName: "地理",
      quizTitle: "title=geography01",
      finalJudge: false,
      status: "未回答",
      correctCount: 0,
      question: [
        {
          questionNumber: "問題１",
          id: "01",
          question: "東京の首都は？",
          answers: ["a.川崎", "b.東京", "c.大阪", "d.名古屋"],
          correct: "b.東京",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題２",
          id: "02",
          question: "イギリスの首都は？",
          answers: ["a.川崎", "b.ロンドン", "c.大阪", "d.名古屋"],
          correct: "b.ロンドン",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題３",
          id: "03",
          question: "オーストラリアの首都は？",
          answers: ["a.川崎", "b.ロンドン", "c.キャンベラ", "d.名古屋"],
          correct: "c.キャンベラ",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題4",
          id: "04",
          question: "イタリアの首都は？",
          answers: ["a.ローマ", "b.ロンドン", "c.キャンベラ", "d.名古屋"],
          correct: "a.ローマ",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題５",
          id: "05",
          question: "アメリカ合衆国の首都は？",
          answers: ["ワシントンD.C.", "ニューヨーク", "ロサンゼルス", "シカゴ"],
          correct: "ワシントンD.C.",
          yourAnswer: null,
          judge: null,
        },
      ],
    },
  ],
  [
    {
      quizName: "英語",
      quizTitle: "title=english01",
      finalJudge: false,
      status: "未回答",
      correctCount: 0,
      question: [
        {
          questionNumber: "問題１",
          id: "01",
          question: "Which planet is known as the Red Planet?",
          answers: ["Venus", "Jupiter", "Mars", "Saturn"],
          correct: "Mars",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題２",
          id: "02",
          question: "Who wrote 'Romeo and Juliet'?",
          answers: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
          correct: "William Shakespeare",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題3",
          id: "03",
          question: "What is the opposite of 'brave'?",
          answers: ["fearful", "strong", "kind", "happy"],
          correct: "fearful",
          yourAnswer: null,
          judge: null,
        },
      ],
    },
  ],
  [
    {
      quizName: "歴史",
      quizTitle: "title=history01",
      finalJudge: false,
      status: "未回答",
      correctCount: 0,
      question: [
        {
          questionNumber: "問題１",
          id: "01",
          question: "フランス革命時にギロチンにかけられたフランスの政治家は誰ですか？",
          answers: ["ルイ16世", "マリー・アントワネット", "ロベスピエール", "ナポレオン・ボナパルト"],
          correct: "ロベスピエール",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題２",
          id: "02",
          question: "アメリカ独立宣言を起草した人物は誰ですか？",
          answers: ["トマス・ジェファーソン", "ジョージ・ワシントン", "ジョン・アダムズ", "ベンジャミン・フランクリン"],
          correct: "トマス・ジェファーソン",
          yourAnswer: null,
          judge: null,
        },
      ],
    },
  ],
  [
    {
      quizName: "理科",
      quizTitle: "title=chemistry01",
      finalJudge: false,
      status: "未回答",
      correctCount: 0,
      question: [
        {
          questionNumber: "問題１",
          id: "01",
          question: "水の化学式は？",
          answers: ["HO", "H2O", "CO2", "NaCl"],
          correct: "H2O",
          yourAnswer: null,
          judge: null,
        },
        {
          questionNumber: "問題２",
          id: "02",
          question: "酸素の化学記号は？",
          answers: ["O", "Ox", "O2", "Oh"],
          correct: "O",
          yourAnswer: null,
          judge: null,
        },
      ],
    },
  ],
];
